import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import '@/styles/global.scss';
import { Header } from '@/components/Header';
import Provider  from '../components/Provider';

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: 'GGNEWS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={roboto.className}>

        <Provider>
          <Header />
          {children}
        </Provider>

      </body>
    </html>
  )
}
